model:
    name: "nguyenvulebinh"
    model_ckpt: nguyenvulebinh/vi-mrc-large
    tokenizer_ckpt: nguyenvulebinh/vi-mrc-large
    device: "cuda"

lucene: # all args must be followed to `pyserini` package
    collection: JsonCollection 
    input: ./pyserini/ 
    language: vi 
    index: ./indexes/test_subprocess 
    generator: DefaultLuceneDocumentGenerator 
    stemmer: none 
    threads: 1

question_path: ./dataset/zac2022_testa_only_question.json

title_id_file: ./dataset/titles_id.pkl

raw_candidate_answers: ./outputs/raw_candidate_answers.json

submission_name: ./outputs/submission.json
